setup-envorinment: Corrected ScriptCheck and fixed issues

diff --git a/tools/setup-environment b/tools/setup-environment
--- a/tools/setup-environment
+++ b/tools/setup-environment
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 # -*- mode: shell-script; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
 #
 # Copyright (C) 2012, 2013, 2016 O.S. Systems Software LTDA.
@@ -20,18 +20,18 @@
 # Add options for the script
 # Copyright (C) 2013 Freescale Semiconductor, Inc.
 
-CWD=$(pwd)
+CWD=${PWD}
 PROGNAME="setup-environment"
 
 usage()
 {
-    echo -e "
-Usage: MACHINE=<machine> DISTRO=<distro> . $PROGNAME [-i] [-r] [-v] [-a] [-h] <build-dir>
-Usage:                                   . $PROGNAME [-i] [-r] [-v] [-a] [-h] <build-dir>
+    cat << EOF
+Usage: [MACHINE=<machine>] [DISTRO=<distro>] . ${PROGNAME} [-i] [-r] [-v] [-a] [-h] <build-dir>
     <machine>    machine name
     <distro>     distro name
     <build-dir>  build directory
-    Optional parameters: [-i] [-r] [-h]
+
+    Optional parameters:
     * [-i]: Internal build
     * [-r]: Add Radio DVK to setup
     * [-a]: Development desktop setup (enable all)
@@ -46,22 +46,21 @@ bitbake on the build directory.
 The second usage is for using an existing build directory. In this case,
 the script prepares the calling shell for running bitbake on the build
 directory <build-dir>. The build directory configuration is unchanged.
-"
-        echo -e "
-Supported machines: `echo; ls sources/meta-summit-som/conf/machine/*.conf \
-| sed s/\.conf//g | sed -r 's/^.+\///' | xargs -I% echo -e "\t%"`
 
-Supported distros: `echo; ls sources/meta-summit-som/conf/distro/*.conf \
-| sed s/\.conf//g | sed -r 's/^.+\///' | xargs -I% echo -e "\t%"`
+Supported machines:
+$(basename -as .conf sources/meta-summit-som/conf/machine/*.conf | sed '/^\*/d; s/^/\t/g')
 
+Supported distros:
+$(basename -as .conf sources/meta-summit-som/conf/distro/*.conf | sed '/^\*/d; s/^/\t/g')
+    
 Examples:
 
 - To create a new Yocto build directory:
-  $ MACHINE=imx8mp-summitsom DISTRO=summitsom-wayland . $PROGNAME build
+  $ MACHINE=imx8mp-summitsom DISTRO=summitsom-wayland . ${PROGNAME} build
 
 - To use an existing Yocto build directory:
-  $ . $PROGNAME build
-"
+  $ . ${PROGNAME} build
+EOF
 }
 
 clean_up()
@@ -77,17 +76,17 @@ setup_devel=false
 setup_summit=false
 setup_vigiles=false
 
-ARGS=$(getopt -o "hirv" -l "help," --name $PROGNAME -- "$@" )
+ARGS=$(getopt -o "hirv" -l "help," --name ${PROGNAME} -- "$@" )
 # Print the usage menu if invalid options are specified
-if [ $? != 0 -o $# -lt 1 ]; then
+if [ $? != 0 ] || [ $# -lt 1 ]; then
    usage && clean_up
    return 1
 fi
 
-eval set -- "$ARGS"
+eval set -- "${ARGS}"
 while true;
 do
-    case $1 in
+    case ${1} in
         -h|--help)
            usage
            clean_up
@@ -116,25 +115,26 @@ do
     shift
 done
 
-if [ "$(whoami)" = "root" ]; then
+if [ "$(id -u)" -eq 0 ]; then
     echo "ERROR: do not use the BSP as root. Exiting..."
     clean_up
     return 1
 fi
 
-[ -e $1/conf/local.conf ] && build_dir_setup_enabled=false \
-    || build_dir_setup_enabled=true
+[ -e "${1}/conf/local.conf" ] && build_dir_setup_enabled=false ||
+    build_dir_setup_enabled=true
 
-[ -z "$FSL_EULA_FILE" ] && FSL_EULA_FILE=$CWD/sources/meta-imx/LICENSE.txt
-if [ ! -e $FSL_EULA_FILE ]; then
-    echo -e "ERROR: EULA not found at $FSL_EULA_FILE."
+[ -z "${FSL_EULA_FILE}" ] && FSL_EULA_FILE=${CWD}/sources/meta-imx/LICENSE.txt
+if [ ! -e "${FSL_EULA_FILE}" ]; then
+    echo -e "ERROR: EULA not found at ${FSL_EULA_FILE}."
     clean_up
     return 1
 fi
 
-OEROOT=$PWD/sources/poky
-if [ -e $PWD/sources/oe-core ]; then
-    OEROOT=$PWD/sources/oe-core
+if [ -e "${PWD}/sources/oe-core" ]; then
+    OEROOT=${PWD}/sources/oe-core
+else
+    OEROOT=${PWD}/sources/poky
 fi
 
 if [ -n "${RFPROS_FILESHARE_USER}" ] && [ -n "${RFPROS_FILESHARE_PASS}" ]; then
@@ -142,7 +142,8 @@ if [ -n "${RFPROS_FILESHARE_USER}" ] && [ -n "${RFPROS_FILESHARE_PASS}" ]; then
     BB_ENV_PASSTHROUGH_ADDITIONS="${BB_ENV_PASSTHROUGH_ADDITIONS} RFPROS_FILESHARE_AUTH"
 fi
 
-[ -n "${BR2_DL_DIR}" ] && export DL_DIR="${BR2_DL_DIR}" || export DL_DIR="${HOME}/.br2_dl_dir"
+[ -n "${BR2_DL_DIR}" ] && DL_DIR="${BR2_DL_DIR}" || DL_DIR="${HOME}/.br2_dl_dir"
+export DL_DIR
 BB_ENV_PASSTHROUGH_ADDITIONS="${BB_ENV_PASSTHROUGH_ADDITIONS} DL_DIR"
 
 if [ -n "${VERSION}" ]; then
@@ -151,20 +152,32 @@ if [ -n "${VERSION}" ]; then
     BB_ENV_PASSTHROUGH_ADDITIONS="${BB_ENV_PASSTHROUGH_ADDITIONS} IMAGE_VERSION_SUFFIX SUMMIT_VERSION SUMMIT_RELEASE_STRING"
 fi
 
-TEMPLATECONF=${TEMPLATECONF:-$CWD/sources/meta-summit-som/conf/templates/default} . $OEROOT/oe-init-build-env $CWD/$1
+# shellcheck source=/dev/null
+TEMPLATECONF=${TEMPLATECONF:-${CWD}/sources/meta-summit-som/conf/templates/default} \
+    . "${OEROOT}/oe-init-build-env" "${CWD}/${1}"
 
 if ${build_dir_setup_enabled}; then 
     # Change settings according environment
-    [ -n "${MACHINE}" ] && sed -e "s,MACHINE ??=.*,MACHINE ??= '$MACHINE',g" -i conf/local.conf
-    [ -n "${DISTRO}" ] && sed -e "s,DISTRO ?=.*,DISTRO ?= '$DISTRO',g" -i conf/local.conf
+    [ -n "${MACHINE}" ] && sed -e "s,MACHINE ??=.*,MACHINE ??= '${MACHINE}',g" -i conf/local.conf
+    [ -n "${DISTRO}"  ] && sed -e "s,DISTRO ?=.*,DISTRO ?= '${DISTRO}',g" -i conf/local.conf
 
-    ${setup_summit} && echo 'OVERRIDES .= ":summit-internal"' >> conf/local.conf
+    {
+        ${setup_summit} || ! ${setup_devel} || printf '# '
+        echo 'OVERRIDES .= ":summit-internal"'
+        
+        ${setup_vigiles} || printf '# '
+        echo 'INHERIT += "vigiles"'
+    } >> conf/local.conf
 
-    ${setup_vigiles} && ${setup_devel} && echo -n '#'
-    ${setup_vigiles} &&  echo 'INHERIT += "vigiles"' >> conf/local.conf
-
-    ${setup_summit} && echo 'BBLAYERS += "${BSPDIR}/sources/meta-summit-radio-mfg"'  >> conf/bblayers.conf
-    ${setup_radio} && echo 'BBLAYERS += "${BSPDIR}/sources/meta-summit-rdvk"' >> conf/bblayers.conf
+    {
+        ${setup_summit} || printf '# '
+        # shellcheck disable=SC2016
+        echo 'BBLAYERS += "${BSPDIR}/sources/meta-summit-radio-mfg"'
+        
+        ${setup_radio} || printf '# '
+        # shellcheck disable=SC2016
+        echo 'BBLAYERS += "${BSPDIR}/sources/meta-summit-rdvk"'
+    } >> conf/bblayers.conf
 fi
 
 # Handle EULA setting
@@ -175,12 +188,12 @@ if grep -q '^\s*ACCEPT_FSL_EULA\s*=\s*["'\'']..*["'\'']' conf/local.conf; then
     EULA_ACCEPTED=1
 fi
 
-if [ -z "$EULA_ACCEPTED" ] && [ -n "$EULA" ]; then
+if [ -z "${EULA_ACCEPTED}" ] && [ -n "${EULA}" ]; then
     # The FSL EULA is not set as accepted in local.conf, but the EULA
     # variable is set in the environment, so we just configure
     # ACCEPT_FSL_EULA in local.conf according to $EULA.
-    echo "ACCEPT_FSL_EULA = \"$EULA\"" >> conf/local.conf
-elif [ -n "$EULA_ACCEPTED" ]; then
+    echo "ACCEPT_FSL_EULA = \"${EULA}\"" >> conf/local.conf
+elif [ -n "${EULA_ACCEPTED}" ]; then
     # The FSL EULA has been accepted once, so ACCEPT_FSL_EULA is set
     # in local.conf.  No need to do anything.
     :
@@ -198,13 +211,13 @@ EOF
 
     sleep 4
 
-    more -d $FSL_EULA_FILE
+    more -d "${FSL_EULA_FILE}"
     echo
     REPLY=
-    while [ -z "$REPLY" ]; do
-        echo -n "Do you accept the EULA you just read? (y/n) "
-        read REPLY
-        case "$REPLY" in
+    while [ -z "${REPLY}" ]; do
+        printf "Do you accept the EULA you just read? (y/n) "
+        read -r REPLY
+        case "${REPLY}" in
             y|Y)
             echo "EULA has been accepted."
             echo "ACCEPT_FSL_EULA = \"1\"" >> conf/local.conf
